### ISSUE TITLE
Onboarding `onClose` message gets shown after `appStart` happened

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/tray-electron#101]
After finish the on boarding process, and having the tray running, when click on exit we have a wrong alert message:

![image](https://user-images.githubusercontent.com/1957899/150366607-fa891827-5fe4-4318-ac3c-6072ce8d589c.png)

**Comment by gbraad** [comment]
This is right AFTER finishing the onboarding process and exiting from the menu?

This does not happen at the moment the onboarding did not happen for the session.

**Comment by gbraad** [comment]
https://github.com/code-ready/tray-electron/blob/1bc18d6731081dbb2bf288cc971f4d2a1e8a50cc/main.js#L117-L132

What I think is happening is that the `onClose` event is still active and gets triggered when the `destroy()` gets called on `setupWindow`. 

---

Perhaps introduce and check `bool isOnboarding` for the state we are in. This would prevent having to add the event and removing it again.

https://github.com/code-ready/tray-electron/blob/1bc18d6731081dbb2bf288cc971f4d2a1e8a50cc/main.js#L583-L586

This is where we disable the `isOnboarding` flag
